// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsHtzV_PrALTKeGMjjjDqKpBIFp2zC6-k',
    appId: '1:966957260822:web:5208944c5ad05f129d5537',
    messagingSenderId: '966957260822',
    projectId: 'leos-mobile-and-web-app',
    authDomain: 'leos-mobile-and-web-app.firebaseapp.com',
    storageBucket: 'leos-mobile-and-web-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRfYqcSCGJGrAOaMn2ai2Av8bswG0B-es',
    appId: '1:966957260822:android:421540ec59391e2d9d5537',
    messagingSenderId: '966957260822',
    projectId: 'leos-mobile-and-web-app',
    storageBucket: 'leos-mobile-and-web-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvDGHLGOL8c69b926bS9OASXi-uCjfkbc',
    appId: '1:966957260822:ios:d3b6ebfc6b34e2639d5537',
    messagingSenderId: '966957260822',
    projectId: 'leos-mobile-and-web-app',
    storageBucket: 'leos-mobile-and-web-app.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvDGHLGOL8c69b926bS9OASXi-uCjfkbc',
    appId: '1:966957260822:ios:d3b6ebfc6b34e2639d5537',
    messagingSenderId: '966957260822',
    projectId: 'leos-mobile-and-web-app',
    storageBucket: 'leos-mobile-and-web-app.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsHtzV_PrALTKeGMjjjDqKpBIFp2zC6-k',
    appId: '1:966957260822:web:201225a0c2d9ef1a9d5537',
    messagingSenderId: '966957260822',
    projectId: 'leos-mobile-and-web-app',
    authDomain: 'leos-mobile-and-web-app.firebaseapp.com',
    storageBucket: 'leos-mobile-and-web-app.appspot.com',
  );
}
